# Use postgres/example user/password credentials
version: '3.8'

services:
  db:
    container_name: my-postgres
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: asdf
      POSTGRES_PASSWORD: asdf
      POSTGRES_DB: asdf
  adminer:
    container_name: my-adminer
    image: adminer
    restart: always
    ports:
      - 8899:8080
