server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        grpc.server.calls: true
        http.server.requests: true
      percentiles:
        http.server.requests: 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.9
      slo:
        http.server.requests: 1, 500

debug: true
